### ISSUE TITLE
Sometimes, it doesnt work. It doesnt leave the meet automatically.

### ISSUE THREAD

**Issue by Sid110307** [ProgrammerGaurav/Google-Meet-Hack#2]

**Comment by ProgrammerGaurav** [comment]
I and my friends have tested it several times and never faces any problem, can you please specify any specific case when it didn't work.

**Comment by antsustr** [comment]
Possible fix? #4

**Comment by ProgrammerGaurav** [comment]
> Possible fix? #4

Yess Thank You
